
[options]
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = true
	#Message that displays when Teleport is blocked
	blockedmessage = "Before entering hell, you shall win against the devil's ante so fortune may be in your favor"
	#Title for the Advancements
	craftedmessage = "Tearing the interdimensional loom"
	#Description for the Advancements
	description = "Defeat Dama Fortune and get Fortune's Favor to get acces to the Nether"
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "meetyourfight:fortunes_favor"
	#Comma seperated list of Dimension Resource Names
	dimresname = "minecraft:the_nether"
	#Comma seperated list of Dimension Display Names
	dimnames = "Nether"

