
[server]
	#Login Timeout(s)
	#Range: 0 ~ 1200
	secs = 600
	#Commands in whitelist can be executed before player login.
	commandNames = []
	#Which storage provider to use
	#Simplelogin provides to available providers by default:
	#simplelogin:file -> file based storage
	#simplelogin:sqlite -> sqlite based storage
	#Note that you need to add JDBC-sqlite yourself if you want to use sqlite
	storageProvider = "simplelogin:file"
	#Default game type switched after player login
	#0,1,2,3 represents survival,creative,adventure,spectator
	#Range: 0 ~ 3
	defaultGameType = 0
	#Player login handler plugins to load
	#simplelogin:protect_coord is disabled by default, add to here to enable coord protect feature
	plugins = ["simplelogin:auto_save", "simplelogin:resend_request", "simplelogin:restrict_game_type", "simplelogin:restrict_movement", "simplelogin:timeout"]

