"Max Distant Fire (default: 256)" = 256
"Max Smoke Columns (default: 256)" = 256
"Falling Ash Near Smoke Columns (default: true)" = true
"Music Volume (default: 1.0)" = 1.0
"Music Obeys Music Volume Slider (default: false)" = false
"Camera Shake Intensity (default: 1.0)" = 1.0
"Distant Fire Opacity (default: 0.1)" = 0.1
"Distant Fire Colour (default: 0xFF552A)" = 16733482
"Only Play One Music Track (default: false)" = false
"Wither Shine Opacity (default: 0.1)" = 0.1
"Distant Fire Colour (default: 0xFFFFFF)" = 16777215
"Distant Fire Colour (default: 0x5be3e8)" = 6022120
"Remove Wither Wings (default: false)" = false
"Wither Ribcage Item (default: \"minecraft:nether_star\")" = "minecraft:nether_star"

